DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS invoice_types;
DROP TABLE IF EXISTS account_terms;
DROP TABLE IF EXISTS entities;
DROP TABLE IF EXISTS material_notes;
DROP TABLE IF EXISTS material_subjects;
DROP TABLE IF EXISTS invoices;
DROP TYPE IF EXISTS e_entity_type;
DROP TYPE IF EXISTS e_material_type;
