DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS invoice_types CASCADE;
DROP TABLE IF EXISTS account_terms CASCADE;
DROP TABLE IF EXISTS entities CASCADE;
DROP TABLE IF EXISTS material_notes CASCADE;
DROP TABLE IF EXISTS material_subjects CASCADE;
DROP TYPE IF EXISTS e_entity_type;
DROP TYPE IF EXISTS e_material_type;
